import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script></head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
